language: java
sudo: false
install: true

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

install:
  - gradle wrapper --gradle-version 4.4

deploy:
  provider: azure_web_apps
  username: stc9
  password: stc9academy
  site: stc9academy
  verbose: true

